---
default:
  app_name: FusionServe
  pg_user: 'fras.marco'
  pg_database: 'fusionserve'
  pg_app_schema: 'app_public'
  echo_sql: False
development:
  pg_host: ep-crimson-queen-09889237.eu-central-1.aws.neon.tech
  echo_sql: True
